# Generated by Django 3.0.5 on 2020-04-06 23:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_personals', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('1', 'Father'), ('2', 'Mother'), ('3', 'Sibling'), ('4', 'Children'), ('5', 'Husband'), ('6', 'Wife'), ('99', 'Other')], default='99', max_length=256, verbose_name='relation')),
                ('relationship', models.CharField(blank=True, max_length=256, null=True, verbose_name='Relationship')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of birth')),
                ('job', models.CharField(max_length=256, verbose_name='Job')),
                ('address', models.TextField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('institution', models.CharField(max_length=256, verbose_name='Institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date end')),
                ('status', models.CharField(choices=[('FNS', 'FINISHED'), ('ONG', 'ONGOING'), ('UNF', 'UNFINISHED')], default='ONG', max_length=5, verbose_name='Current status')),
                ('major', models.CharField(blank=True, help_text='ex: Information System or Accounting', max_length=256, null=True, verbose_name='Major')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_educations', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonFormalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('institution', models.CharField(max_length=256, verbose_name='Institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date end')),
                ('status', models.CharField(choices=[('FNS', 'FINISHED'), ('ONG', 'ONGOING'), ('UNF', 'UNFINISHED')], default='ONG', max_length=5, verbose_name='Current status')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_formal_educations', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Primary')),
                ('name', models.CharField(help_text='E.g. Home Address or Office Address', max_length=256, null=True, verbose_name='Name')),
                ('street', models.CharField(blank=True, max_length=512, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='Province')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Country')),
                ('zipcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='Zip Code')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='Fax')),
                ('whatsapp', models.CharField(blank=True, max_length=128, null=True, verbose_name='Whatsapp')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='Website')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('publisher', models.CharField(blank=True, max_length=256, null=True, verbose_name='Publisher')),
                ('date_published', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published date')),
                ('permalink', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skill level')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter', models.CharField(blank=True, help_text='twitter username, without the @', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username, without the @', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel or user account URL', null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=256, verbose_name='Organization')),
                ('position', models.CharField(max_length=256, verbose_name='Position')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date end')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INC', 'Inactive')], default='ACT', max_length=5, verbose_name='Status')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('institution', models.CharField(max_length=256, verbose_name='Institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date end')),
                ('status', models.CharField(choices=[('FNS', 'FINISHED'), ('ONG', 'ONGOING'), ('UNF', 'UNFINISHED')], default='ONG', max_length=5, verbose_name='Current status')),
                ('department', models.CharField(max_length=256, verbose_name='Department')),
                ('position', models.CharField(max_length=256, verbose_name='Position')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('employment', models.CharField(choices=[('CTR', 'Contract'), ('FXD', 'Fixed'), ('OSR', 'Outsource'), ('ELS', 'Else')], default='CTR', max_length=5, verbose_name='Employment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='django_personals.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
